# Generated by Django 5.1.3 on 2026-03-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('url_archivo', models.CharField(max_length=500)),
                ('tamanio_bytes', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'db_table': 'adjunto',
            },
        ),
        migrations.CreateModel(
            name='HistorialTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('TICKET_CREADO', 'Ticket creado'), ('AGENTE_ASIGNADO', 'Agente asignado'), ('ESTADO_CAMBIADO', 'Estado cambiado'), ('COMENTARIO_AGREGADO', 'Comentario agregado'), ('CONFIRMACION_CLIENTE', 'Confirmación cliente'), ('TICKET_CERRADO', 'Ticket cerrado'), ('REASIGNACION', 'Reasignación'), ('TICKET_ELIMINADO', 'Ticket eliminado'), ('CAMBIO_PRIORIDAD', 'Cambio de prioridad')], max_length=50)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de ticket',
                'verbose_name_plural': 'Historial de tickets',
                'db_table': 'historial_ticket',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('SOLUCIONADO', 'Solucionado'), ('RECHAZADO', 'Rechazado')], max_length=50)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('solucionado', 'Solucionado'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='en_proceso', max_length=15)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('motivo_escalamiento', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_primera_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_solucionado', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('chatbot_enviado', models.BooleanField(default=False)),
                ('chatbot_resolvio', models.BooleanField(default=False)),
                ('horas_limite_confirmacion', models.IntegerField(default=72)),
                ('comentario_solucion', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
            },
        ),
    ]
