# Generated by Django 5.1.3 on 2026-04-30 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        ('operaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('eliminado', 'Eliminado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, db_column='id_area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='instituciones.area')),
            ],
            options={
                'verbose_name': 'Categoría de incidencia',
                'verbose_name_plural': 'Categorías de incidencia',
                'db_table': 'categoria_incidencia',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('comentario_solucion', models.TextField(blank=True, default='')),
                ('motivo_escalamiento', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('solucionado', 'Solucionado'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado'), ('escalado', 'Escalado')], default='en_proceso', max_length=15)),
                ('prioridad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_primera_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_solucionado', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('chatbot_enviado', models.BooleanField(default=False)),
                ('chatbot_resolvio', models.BooleanField(default=False)),
                ('horas_limite_confirmacion', models.IntegerField(default=72)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agente_asignado', models.ForeignKey(blank=True, db_column='id_agente_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='usuarios.agente')),
                ('agente_escalado', models.ForeignKey(blank=True, db_column='id_agente_escalado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_escalados', to='usuarios.agente')),
                ('area', models.ForeignKey(blank=True, db_column='id_area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='instituciones.area')),
                ('canal', models.ForeignKey(db_column='id_canal', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='operaciones.canalentrada')),
                ('categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.categoriaincidencia')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='usuarios.cliente')),
                ('sistema', models.ForeignKey(db_column='id_sistema', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='instituciones.sistema')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='SatisfaccionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.SmallIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.OneToOneField(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='satisfaccion', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Satisfacción de ticket',
                'verbose_name_plural': 'Satisfacciones de tickets',
                'db_table': 'satisfaccion_ticket',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('SOLUCIONADO', 'Solucionado'), ('RECHAZADO', 'Rechazado')], max_length=50)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(db_column='id_destinatario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='HistorialTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('TICKET_CREADO', 'Ticket creado'), ('AGENTE_ASIGNADO', 'Agente asignado'), ('ESTADO_CAMBIADO', 'Estado cambiado'), ('COMENTARIO_AGREGADO', 'Comentario agregado'), ('CONFIRMACION_CLIENTE', 'Confirmación del cliente'), ('TICKET_CERRADO', 'Ticket cerrado'), ('REASIGNACION', 'Reasignación'), ('TICKET_ELIMINADO', 'Ticket eliminado'), ('CAMBIO_PRIORIDAD', 'Cambio de prioridad')], max_length=50)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, db_column='id_autor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_generados', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Historial de ticket',
                'verbose_name_plural': 'Historial de tickets',
                'db_table': 'historial_ticket',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('url_archivo', models.CharField(max_length=500)),
                ('tamanio_bytes', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, db_column='subido_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'db_table': 'adjunto',
            },
        ),
        migrations.AddIndex(
            model_name='categoriaincidencia',
            index=models.Index(fields=['area'], name='idx_categoria_id_area'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['cliente'], name='idx_ticket_id_cliente'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['canal'], name='idx_ticket_id_canal'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sistema'], name='idx_ticket_id_sistema'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['categoria'], name='idx_ticket_id_categoria'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['area'], name='idx_ticket_id_area'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['agente_asignado'], name='idx_ticket_id_agente_asignado'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='idx_ticket_estado'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridad'], name='idx_ticket_prioridad'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='idx_ticket_created_at'),
        ),
        migrations.AddIndex(
            model_name='satisfaccionticket',
            index=models.Index(fields=['ticket'], name='idx_satisfaccion_id_ticket'),
        ),
        migrations.AddIndex(
            model_name='satisfaccionticket',
            index=models.Index(condition=models.Q(('respondido_en__isnull', False)), fields=['respondido_en'], name='idx_satisfaccion_respondido'),
        ),
        migrations.AddIndex(
            model_name='satisfaccionticket',
            index=models.Index(condition=models.Q(('puntuacion__isnull', False)), fields=['puntuacion'], name='idx_satisfaccion_puntuacion'),
        ),
        migrations.AddConstraint(
            model_name='satisfaccionticket',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacion__isnull', True), models.Q(('puntuacion__gte', 1), ('puntuacion__lte', 5)), _connector='OR'), name='chk_satisfaccion_puntuacion'),
        ),
        migrations.AddConstraint(
            model_name='satisfaccionticket',
            constraint=models.CheckConstraint(condition=models.Q(('respondido_en__isnull', True), ('respondido_en__gte', models.F('enviado_en')), _connector='OR'), name='chk_satisfaccion_fechas'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['ticket'], name='idx_notificacion_id_ticket'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario'], name='idx_notif_destinatario'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estado'], name='idx_notificacion_estado'),
        ),
        migrations.AddIndex(
            model_name='historialticket',
            index=models.Index(fields=['ticket'], name='idx_historial_id_ticket'),
        ),
        migrations.AddIndex(
            model_name='historialticket',
            index=models.Index(fields=['tipo_evento'], name='idx_historial_tipo_evento'),
        ),
        migrations.AddIndex(
            model_name='adjunto',
            index=models.Index(fields=['ticket'], name='idx_adjunto_id_ticket'),
        ),
        migrations.AddConstraint(
            model_name='adjunto',
            constraint=models.CheckConstraint(condition=models.Q(('tamanio_bytes__isnull', True), ('tamanio_bytes__lte', 10485760), _connector='OR'), name='chk_adjunto_tamanio'),
        ),
    ]
