# Generated by Django 5.1.3 on 2026-04-21 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        ('operaciones', '0002_initial'),
        ('tickets', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunto',
            name='subido_por',
            field=models.ForeignKey(blank=True, db_column='subido_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialticket',
            name='autor',
            field=models.ForeignKey(blank=True, db_column='id_autor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(db_column='id_destinatario', on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='canal',
            field=models.ForeignKey(db_column='id_canal', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='operaciones.canalentrada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sistema',
            field=models.ForeignKey(db_column='id_sistema', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='instituciones.sistema'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='solicitud',
            field=models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.solicitud'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='agente_asignado',
            field=models.ForeignKey(blank=True, db_column='id_agente_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='usuarios.agente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='agente_escalado',
            field=models.ForeignKey(blank=True, db_column='id_agente_escalado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_escalados', to='usuarios.agente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='area',
            field=models.ForeignKey(blank=True, db_column='id_area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='operaciones.area'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitud',
            field=models.OneToOneField(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='tickets.solicitud'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='ticket',
            field=models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='historialticket',
            name='ticket',
            field=models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket'),
        ),
    ]
