# Generated by Django 5.1.3 on 2026-04-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('correo', 'Correo'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('formulario_web', 'Formulario web'), ('chatbot_movil', 'Chatbot móvil'), ('llamada', 'Llamada')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('eliminado', 'Eliminado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canal de entrada',
                'verbose_name_plural': 'Canales de entrada',
                'db_table': 'canal_entrada',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Completo', 'Completo'), ('Fin de semana', 'Fin de semana'), ('Personalizado', 'Personalizado')], max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lunes', models.BooleanField(default=False)),
                ('martes', models.BooleanField(default=False)),
                ('miercoles', models.BooleanField(default=False)),
                ('jueves', models.BooleanField(default=False)),
                ('viernes', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='AgenteArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(db_column='id_agente', on_delete=django.db.models.deletion.PROTECT, related_name='agente_areas', to='usuarios.agente')),
                ('area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.PROTECT, related_name='agente_areas', to='instituciones.area')),
            ],
            options={
                'verbose_name': 'Agente-Área',
                'verbose_name_plural': 'Agentes-Áreas',
                'db_table': 'agente_area',
                'indexes': [models.Index(fields=['agente'], name='idx_agente_area_id_agente')],
                'constraints': [models.UniqueConstraint(fields=('agente', 'area'), name='uq_agente_area')],
            },
        ),
        migrations.CreateModel(
            name='AgenteHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('agente', models.ForeignKey(db_column='id_agente', on_delete=django.db.models.deletion.PROTECT, related_name='agente_horarios', to='usuarios.agente')),
                ('horario', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.PROTECT, related_name='agente_horarios', to='operaciones.horario')),
            ],
            options={
                'verbose_name': 'Agente-Horario',
                'verbose_name_plural': 'Agentes-Horarios',
                'db_table': 'agente_horario',
                'indexes': [models.Index(fields=['agente'], name='idx_agente_horario_id_agente')],
            },
        ),
    ]
