# Generated by Django 5.1.3 on 2026-04-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentearea',
            name='agente',
            field=models.ForeignKey(db_column='id_agente', on_delete=django.db.models.deletion.PROTECT, related_name='agente_areas', to='usuarios.agente'),
        ),
        migrations.AddField(
            model_name='agentehorario',
            name='agente',
            field=models.ForeignKey(db_column='id_agente', on_delete=django.db.models.deletion.PROTECT, related_name='agente_horarios', to='usuarios.agente'),
        ),
        migrations.AddField(
            model_name='agentearea',
            name='area',
            field=models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.PROTECT, related_name='agente_areas', to='operaciones.area'),
        ),
        migrations.AddField(
            model_name='agentehorario',
            name='horario',
            field=models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.PROTECT, related_name='agente_horarios', to='operaciones.horario'),
        ),
        migrations.AddConstraint(
            model_name='agentearea',
            constraint=models.UniqueConstraint(fields=('agente', 'area'), name='uq_agente_area'),
        ),
    ]
