# Generated by Django 5.1.3 on 2026-04-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('eliminado', 'Eliminado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='InstitucionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(db_column='id_institucion', on_delete=django.db.models.deletion.PROTECT, related_name='institucion_sistemas', to='instituciones.institucion')),
            ],
            options={
                'verbose_name': 'Institución-Sistema',
                'verbose_name_plural': 'Instituciones-Sistemas',
                'db_table': 'institucion_sistema',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('eliminado', 'Eliminado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instituciones', models.ManyToManyField(related_name='sistemas', through='instituciones.InstitucionSistema', to='instituciones.institucion')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'db_table': 'sistema',
            },
        ),
        migrations.AddField(
            model_name='institucionsistema',
            name='sistema',
            field=models.ForeignKey(db_column='id_sistema', on_delete=django.db.models.deletion.PROTECT, related_name='institucion_sistemas', to='instituciones.sistema'),
        ),
        migrations.AddConstraint(
            model_name='institucionsistema',
            constraint=models.UniqueConstraint(fields=('institucion', 'sistema'), name='uq_inst_sistema'),
        ),
    ]
